include: package:lint/analysis_options.yaml

analyzer:
  errors:
    missing_required_param: warning
    missing_return: warning
    todo: info
    

linter:
  rules:
    prefer_single_quotes: true
    prefer_relative_imports: true
    constant_identifier_names: false
    sort_constructors_first: false
    avoid_classes_with_only_static_members: false