name: lifelog
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  app_runner: ^1.0.2
  flutter: 
    sdk: flutter
  flutter_form_builder: ^6.0.1
  flutter_screenutil: ^5.0.0+2
  get: ^4.3.8
  get_storage: ^2.0.3
  intl: ^0.17.0
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  supabase_flutter: ^0.2.1

dev_dependencies: 
  flutter_launcher_icons: ^0.9.1
  flutter_test: 
    sdk: flutter
  lint: ^1.5.3

flutter: 
  uses-material-design: true

